### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by SalomonBrys** [qoomon/git-conventional-commits#107]
```
> node --version 
v18.9.0
```

```
> git-conventional-commits --version
2.1.1
```

```
> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

```
> cat git-conventional-commits.json 
{
  "convention" : {
    "commitTypes": [
      "feat",
      "fix",
      "perf",
      "refactor",
      "style",
      "test",
      "build",
      "ops",
      "docs",
      "chore",
      "merge",
      "revert"
    ],
    "commitScopes": [],
    "releaseTagGlobPattern": "v[0-9].*",
    "issueRegexPattern": "(^|\\s)#\\d+(\\s|$)"
  },

  "changelog" : {
    "commitTypes": [
      "feat",
      "fix",
      "perf",
      "merge"
    ],
    "commitIgnoreRegexPattern": "^WIP ",
    "headlines": {
      "feat": "Features",
      "fix": "Bug Fixes",
      "perf": "Performance Improvements",
      "merge": "Merged Branches",
      "breakingChange": "BREAKING CHANGES"
    },

    "commitUrl": "https://[REDACTED]/commit/%commit%",
    "commitRangeUrl": "https://[REDACTED]/compare/%from%...%to%?diff=split"
  }
}

```

```
> git-conventional-commits version
...
TypeError: Cannot read properties of undefined (reading 'match')
    at parseCommitSubject (/opt/homebrew/lib/node_modules/git-conventional-commits/lib/gitCommitConvention.js:90:41)
    at parseCommitSubject (/opt/homebrew/lib/node_modules/git-conventional-commits/lib/gitCommitConvention.js:105:43)
    at parseCommit (/opt/homebrew/lib/node_modules/git-conventional-commits/lib/gitCommitConvention.js:68:37)
    at Array.map (<anonymous>)
    at module.exports.getCommitLog (/opt/homebrew/lib/node_modules/git-conventional-commits/lib/gitCommitConvention.js:15:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports.getVersion (/opt/homebrew/lib/node_modules/git-conventional-commits/lib/gitCommitConvention.js:45:30)
    at async exports.handler (/opt/homebrew/lib/node_modules/git-conventional-commits/lib/commands/commandVersion.js:24:33)
```

**Comment by qoomon** [comment]
feel free to tray version `2.1.2`

**Comment by SalomonBrys** [comment]
Confirm fix.
Thanks 👍
